# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FormView' do

  pod 'Masonry'
  pod 'TransitionKit', :git => 'https://github.com/raumfeld/TransitionKit.git', :branch => 'master'
  pod 'YYModel'
  
  pod 'Alpha'
  
  pod 'SDWebImage'

end
